name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "45 5 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is inactive for long time"
          stale-pr-message: "This pr is inactive for long time"
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
